FROM gmauro/ansible:2.6_debian8
MAINTAINER Gianmauro Cuccuru <gmauro@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN git clone https://github.com/gmauro/ansible-docker \
 && cd ansible-docker \
 && ansible-playbook -i localhost, local.yml -e "@defaults/main.yml"
