- name: Import the repository key
  apt_key:
    id=0EBFCD88
    url='https://download.docker.com/linux/{{ distribution_codename }}/gpg'
    state=present

- name: Create the repo source file
  apt_repository:
    repo='deb [arch=amd64] https://download.docker.com/linux/{{ distribution_codename }} {{ ansible_distribution_release }} stable'
    state=present
    filename='docker'

- name: APT update
  apt: update_cache={{ update_cache }} cache_valid_time=3600
