- name: Install the latest version of Docker CE
  apt:
    name: "{{ packages }}"
    state: "{{ packages_state }}"
  vars:
    packages:
    - docker-ce

- name: Install requirements for docker-py python package
  apt:
    name: "{{ packages }}"
    state: "{{ packages_state }}"
  vars:
    packages:
    - python-pip
    - virtualenv
  when:
    - install_docker_py

- name: Install docker-py python package.
  pip:
    name: docker
  when:
    - install_docker_py