- name: Install the latest version of Docker CE
  apt:
    name: "{{ packages }}"
    state: "{{ docker_version }}"
  vars:
    packages:
    - docker-ce
  when:
    - install_docker
    - docker_version == "latest"

- name: Install a specific version of Docker CE
  apt:
    name: "{{ packages }}={{ docker_version }}"
  vars:
    packages:
    - docker-ce
  when:
    - install_docker
    - docker_version != "latest"

- name: Add log limits to docker config
  copy:
    src: daemon.json
    dest: /etc/docker
  notify:
    - restart docker

- name: Install requirements for docker-py python package
  apt:
    name: "{{ packages }}"
    state: "{{ packages_state }}"
  vars:
    packages:
    - python-pip
    - virtualenv
  when:
    - install_docker_py

- name: Install docker-py python package.
  pip:
    name: docker
  when:
    - install_docker_py